# Site settings
title: could be
email: couldbesteph@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A wonderful blog of wonderful things.
owner:
  name: Steph Stevenson # or company name
  url: https://stephstevenson.github.io
first_published: 2017
baseurl: "" # the subpath of your site, e.g. /blog/
url: stephstevenson.github.io # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  stephstevenson

name: 'Stephanie Stevenson'
author: 'Stephanie Stevenson'
author_image: "/images/avatar.jpg"
cover: "/images/cover.jpg"
logo: "/images/logo.jpg"
favicon: "/images/favicon.png"

social:
  # github:
  # deviantart:
  # dribbble:
  # twitter:
  etsy: https://www.etsy.com/people/4waoj5bb
  pinterest: https://pinterest.com/
  linkedin-square: https://linkedin.com/
  # email: /contact/
  #flickr:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #pied-piper:
  #digg:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:

# Build settings
markdown: kramdown
highlighter: rouge
sass:
 style: compressed

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

mailaction: https://getsimpleform.com/messages?form_api_token=b2c41d3e99fac447c26b268851e42028

collections:
  blog:
    output: true
    permalink: /blog/:path/
  archive:
    output: true
    permalink: /archive/:path/

exclude: ['template.md', 'TODO.md', README.md, 'Gulpfile.js', 'package.json', 'node_modules', 'jspm_packages']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page

plugins:
  - jemoji
  - jekyll-paginate
  
html_proofer:
  check_favicon: true
  check_html: true
  allow_hash_href: true
  http_status_ignore: [999,403]
  file_ignore:
    - /a.*regexp*/
    - a_string
  url_ignore:
    - /Hyde/
    - /PlayMusic/
    - /Atomic-Design-UI/
    - /GithubCalendar/
